"""v0.1 initial schema

Revision ID: 36981f27b9a0
Revises: 
Create Date: 2025-10-31 06:04:35.864408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36981f27b9a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('dba_name', sa.String(length=200), nullable=True),
    sa.Column('ein', sa.String(length=15), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_postal', sa.String(length=15), nullable=True),
    sa.Column('default_check_layout', sa.Enum('TOP_SINGLE_STUB', 'BOTTOM_SINGLE_STUB', name='checklayout'), nullable=False),
    sa.Column('default_pay_schedule', sa.Enum('WEEKLY', 'BIWEEKLY', 'SEMI_MONTHLY', 'MONTHLY', name='payschedule'), nullable=True),
    sa.Column('states_of_operation', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deduction_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('pre_tax_fit', sa.Boolean(), nullable=False),
    sa.Column('pre_tax_fica', sa.Boolean(), nullable=False),
    sa.Column('pre_tax_state', sa.Boolean(), nullable=False),
    sa.Column('annual_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earning_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('subject_fit', sa.Boolean(), nullable=False),
    sa.Column('subject_ss', sa.Boolean(), nullable=False),
    sa.Column('subject_medicare', sa.Boolean(), nullable=False),
    sa.Column('subject_futa', sa.Boolean(), nullable=False),
    sa.Column('subject_state', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TERMINATED', 'ON_LEAVE', name='employeestatus'), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('ssn_encrypted', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('hire_date', sa.String(length=10), nullable=True),
    sa.Column('term_date', sa.String(length=10), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_postal', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_pay_setup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('pay_type', sa.Enum('HOURLY', 'SALARY', name='paytype'), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('standard_hours_per_period', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('filing_status_fed', sa.String(length=30), nullable=True),
    sa.Column('dependents_fed', sa.Integer(), nullable=True),
    sa.Column('additional_withholding_fed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('state_primary', sa.String(length=2), nullable=True),
    sa.Column('filing_status_state', sa.String(length=30), nullable=True),
    sa.Column('dependents_state', sa.Integer(), nullable=True),
    sa.Column('additional_withholding_state', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ca_sdi_exempt', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_check',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pay_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('check_number', sa.String(length=40), nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxes_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PRINT', 'PRINTED', 'VOIDED', name='paycheckstatus'), nullable=False),
    sa.Column('printed_at', sa.String(length=32), nullable=True),
    sa.Column('stub_pdf_s3_key', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('check_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'APPROVED', 'FINALIZED', 'VOIDED', name='payrunstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_run_earning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pay_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('earning_type_id', sa.UUID(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('units', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_run_tax',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pay_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('tax_code', sa.String(length=30), nullable=False),
    sa.Column('taxable_wages', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employer_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pay_run_tax')
    op.drop_table('pay_run_earning')
    op.drop_table('pay_run')
    op.drop_table('pay_check')
    op.drop_table('employee_pay_setup')
    op.drop_table('employee')
    op.drop_table('earning_type')
    op.drop_table('deduction_type')
    op.drop_table('company')
    # ### end Alembic commands ###
